### ISSUE TITLE
Pandoc YAML metadata block

### ISSUE THREAD

**Issue by hugoroy** [sciunto/ikiwiki-pandoc#2]
It would be awesome to be able to use pandoc’s metadata feature to replace the way ikiwiki usually required metadata http://johnmacfarlane.net/pandoc/README.html#yaml-metadata-block

**Comment by sciunto** [comment]
Sorry, I have been super slow on this but I just tried with the current plugin and a % title correctly change the title (http://pandoc.org/README.html#metadata-blocks). It's done at the bottom of this file: https://github.com/sciunto/ikiwiki-pandoc/blob/master/pandoc.pm

http://pandoc.org/README.html#metadata-blocks

**Comment by bk** [comment]
My PR #5 adds support for YAML metadata blocks and corrects the handling of title, author and date in the legacy `%`-prefix metadata header type.

**Comment by hugoroy** [comment]
This looks awesome, I will need to test this out when I have more time  :+1:

**Comment by sciunto** [comment]
Closed by #5.
